---
title: "FA21_Search_Jan2020_FR"
author: "Office of Marketing and Brand Management"
date: "3/2/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(salesforcer)
library(knitr)
library(RForcecom)
```


```{r cars}
username <- "christine.iyer@maine.edu"
password <- "1Edithandoliver"
securityToken <- "iFhpXgaXnuP3L5PQr69Zw2yOy"
instanceURL <- "https://login.salesforce.com/"
apiVersion <- "44.0"

#auth <- sf_auth(username = username, password = password, security_token = securityToken,
  #login_url = getOption("https://login.salesforce.com/"))



session <- sf_auth(username, password, securityToken, instanceURL, apiVersion)
```

```{r}
#sf_auth()
```

```{r}

username <- "christine.iyer@maine.edu"
password <- "1EdithandoliveriFhpXgaXnuP3L5PQr69Zw2yOy"
#securityToken <- ""
instanceURL <- "https://na24.salesforce.com/"
apiVersion <- "44.0"





session <- rforcecom.login(username, password, instanceURL,apiVersion  ) 
```


```{r use this}
my_soql <- sprintf("SELECT Id,
                           CreatedDate,
                           Email, 
                           FirstName, 
                           LastName,
                           TargetX_SRMb__Status__c, TargetX_SRMb__Student_Type__c,
                           TargetX_SRMb__Anticipated_Start_Term__c,
                           TargetX_SRMb__Anticipated_Start_Term_Year__c, 
                           App_Application_Date__c,  
                           TargetX_SRMb__Gender__c,  
                           TargetX_SRMb__Last_Data_Input_Source__c,                                                                Initial_Source_Date__c, 
                           Initial_Referral_Source__c, 
                           Recruiting_Category__c,
                           Ref__c, 
                           Primary_State_Code__c, 
                           Lead_Segment_College_Board__c,
                           Lead_Segment_NRCCUA__c
                           
                    FROM Contact 
                    WHERE DAY_ONLY(CreatedDate) > 2020-02-25 
                    AND DAY_ONLY(CreatedDate) < 2020-03-13 
                    AND TargetX_SRMb__Status__c != 'Lead' 
                    AND (Lead_Segment_College_Board__c != ' ' 
                    OR 	Lead_Segment_NRCCUA__c  != ' ') 
                    
                   "
                   )

queried_records <- sf_query(my_soql)

both <- "Both"

queried_records <- queried_records %>% mutate(
  Lead_Segment_College_Board__c = gsub(";", "", Lead_Segment_College_Board__c, fixed = TRUE), 
  Lead_Segment_NRCCUA__c = gsub(";", "", Lead_Segment_NRCCUA__c, fixed = T),
  
  Initial_Code = paste0(Lead_Segment_College_Board__c, Lead_Segment_NRCCUA__c), 
  Initial_Code = gsub("NA" , "", Initial_Code, fixed = T), 
  Initial_Code_len = str_length(Initial_Code), 
  Initial_Code = ifelse(Initial_Code_len > 13,both,Initial_Code ), 
  Vendor = ifelse(grepl("^N", Initial_Code), "NRCCUA", 
                  ifelse(grepl("^P",Initial_Code),  "College Board", 
                         ifelse(Initial_Code == "Both", "Both", "Neither")))) %>% filter(Vendor != "Neither")

```
 



Purchase Dates:
11/10/2015,
3/2/2016,
6/21/2016,
6/28/2016,
10/4/2016,
12/12/2016,
2/14/2017,
6/6/2017,
6/7/2017,
10/12/2017,
2/26/2018,
2/22/2018,
10/18/2018,
12/02/2019, 
12/05/2019, 
02/06/2019


January 2020

```{r}
LeadsUploaded <- read.csv("C:/Users/christine.iyer/Box/Search/FY20_Search/FY20_January_Search/FA21_Junior/FA21_Search_Jan2020_JR.csv", header = T, stringsAsFactors = F)
head(LeadsUploaded)
head(queried_records)
#"Lead.Segment.College.Board"  "Lead.Segment.NRCCUA" 

LeadsUploaded <- LeadsUploaded %>%  mutate(
  Lead.Segment.College.Board = gsub(";", "", Lead.Segment.College.Board, fixed = TRUE), 
  Lead.Segment.NRCCUA = gsub(";", "", Lead.Segment.NRCCUA, fixed = T),
  
  Initial_Code = paste0(Lead.Segment.College.Board, Lead.Segment.NRCCUA), 
  Initial_Code = gsub("NA" , "", Initial_Code, fixed = T), 
  Initial_Code_len = str_length(Initial_Code), 
  Initial_Code = ifelse(Initial_Code_len > 13,both,Initial_Code ), 
  Vendor = ifelse(grepl("^N", Initial_Code), "NRCCUA", 
                  ifelse(grepl("^P",Initial_Code),  "College Board", 
                         ifelse(Initial_Code == "Both", "Both", "Neither"))))

LeadsUploaded %>% group_by(Email, Lead.Segment.College.Board, Lead.Segment.NRCCUA) %>% summarise(n = n()) %>% filter(n>1)



trythis <- merge(LeadsUploaded, queried_records, by = "Email" )
trythis <- trythis %>% mutate(DateCollected = Sys.Date())

trythis
# Don't forget to change the date!

#write.csv(trythis, "C:/Users/christine.iyer/Box/Search/FY20_Search/FY20_January_Search/FA21_Junior/Conversions/Conversion_3-03-20_DeDuped.csv")
trythis %>% 
  #filter(Student.Stage == "Lead") %>% 
  mutate(Name = paste0(Last.Name, ", ", First.Name)) %>% 
  group_by(Vendor,Student.Stage,TargetX_SRMb__Status__c,  Email, Created.Date, Ref__c, Recruiting_Category__c,Recruiting.Category, Lead.Segment.College.Board, Lead.Segment.NRCCUA) %>% summarise(n = n())

```


```{r}
trythis1 <- trythis %>% group_by(Vendor,Primary_State_Code__c) %>% summarise(Inqs = n())
```


```{r}
trythis1 %>% mutate(Recruiting.Category_Geo = ifelse(Primary_State_Code__c == "ME", "In-State", "Out-Of-State")) %>% group_by(Vendor,Recruiting.Category_Geo) %>% summarise(Inqs = sum(Inqs)) %>% filter(Vendor != "Both")

```

